//-----------------------------------------------------------------------------
//
// Copyright(C) 2011, 2012 David Hill
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, see <http://www.gnu.org/licenses/>.
//
//-----------------------------------------------------------------------------
//
// Re-usable header that invokes DO_INIT for every OCODE except OCODE_NONE.
//
//-----------------------------------------------------------------------------


   //-------------------------------------------------------------------------|
   // NOP                                                                     |
   //

   DO_INIT(NOP)


   //-------------------------------------------------------------------------|
   // Arithmetic                                                              |
   //

   DO_INIT(ADD32F)
   DO_INIT(ADD32I)
   DO_INIT(ADD32U)

   DO_INIT(DIV32F)
   DO_INIT(DIV32I)
   DO_INIT(DIV32U)

   DO_INIT(MOD32F)
   DO_INIT(MOD32I)
   DO_INIT(MOD32U)

   DO_INIT(MUL32F)
   DO_INIT(MUL32I)
   DO_INIT(MUL32U)

   DO_INIT(SUB32F)
   DO_INIT(SUB32I)
   DO_INIT(SUB32U)


   //-------------------------------------------------------------------------|
   // Bitwise                                                                 |
   //

   DO_INIT(BITWISE_AND32)
   DO_INIT(BITWISE_IOR32)
   DO_INIT(BITWISE_LSH32)
   DO_INIT(BITWISE_NOT32)
   DO_INIT(BITWISE_RSH32)
   DO_INIT(BITWISE_XOR32)


   //-------------------------------------------------------------------------|
   // Branching                                                               |
   //

   DO_INIT(BRANCH_CASE)
   DO_INIT(BRANCH_GOTO)
   DO_INIT(BRANCH_GOTO_IMM)
   DO_INIT(BRANCH_TABLE)
   DO_INIT(BRANCH_TRUE)
   DO_INIT(BRANCH_ZERO)


   //-------------------------------------------------------------------------|
   // Comparison                                                              |
   //

   DO_INIT(CMP_EQ32F)
   DO_INIT(CMP_EQ32I)

   DO_INIT(CMP_GE32F)
   DO_INIT(CMP_GE32I)
   DO_INIT(CMP_GE32U)

   DO_INIT(CMP_GT32F)
   DO_INIT(CMP_GT32I)
   DO_INIT(CMP_GT32U)

   DO_INIT(CMP_LE32F)
   DO_INIT(CMP_LE32I)
   DO_INIT(CMP_LE32U)

   DO_INIT(CMP_LT32F)
   DO_INIT(CMP_LT32I)
   DO_INIT(CMP_LT32U)

   DO_INIT(CMP_NE32F)
   DO_INIT(CMP_NE32I)


   //-------------------------------------------------------------------------|
   // Conversion                                                              |
   //

   DO_INIT(CONVERT_32F_32I)
   DO_INIT(CONVERT_32I_32F)


   //-------------------------------------------------------------------------|
   // Logical                                                                 |
   //

   DO_INIT(LOGICAL_AND32F)
   DO_INIT(LOGICAL_AND32I)

   DO_INIT(LOGICAL_IOR32F)
   DO_INIT(LOGICAL_IOR32I)

   DO_INIT(LOGICAL_NOT32F)
   DO_INIT(LOGICAL_NOT32I)

   DO_INIT(LOGICAL_XOR32F)
   DO_INIT(LOGICAL_XOR32I)


   //-------------------------------------------------------------------------|
   // Stack-ops                                                               |
   //

   DO_INIT(STACK_DROP32)
   DO_INIT(STACK_DUP32)
   DO_INIT(STACK_SWAP32)


   //-------------------------------------------------------------------------|
   // Trigonometry                                                            |
   //

   DO_INIT(TRIG_COS32F)
   DO_INIT(TRIG_SIN32F)


   //-------------------------------------------------------------------------|
   // Variable Address                                                        |
   //

   DO_INIT(ADDR_AUTO)

   DO_INIT(ADDR_STACK_ADD)
   DO_INIT(ADDR_STACK_ADD_IMM)

   DO_INIT(ADDR_STACK_SUB)
   DO_INIT(ADDR_STACK_SUB_IMM)


   //-------------------------------------------------------------------------|
   // Variable Get                                                            |
   //

   DO_INIT(GET_AUTO32F)
   DO_INIT(GET_AUTO32I)

   DO_INIT(GET_LITERAL32F)
   DO_INIT(GET_LITERAL32I)

   DO_INIT(GET_POINTER32F)
   DO_INIT(GET_POINTER32I)

   DO_INIT(GET_REGISTER32F)
   DO_INIT(GET_REGISTER32I)

   DO_INIT(GET_STATIC32F)
   DO_INIT(GET_STATIC32I)

   DO_INIT(GET_TEMP)


   //-------------------------------------------------------------------------|
   // Variable Set                                                            |
   //

   DO_INIT(SET_AUTO32F)
   DO_INIT(SET_AUTO32I)

   DO_INIT(SET_POINTER32F)
   DO_INIT(SET_POINTER32I)

   DO_INIT(SET_REGISTER32F)
   DO_INIT(SET_REGISTER32I)

   DO_INIT(SET_STATIC32F)
   DO_INIT(SET_STATIC32I)

   DO_INIT(SET_TEMP)


   //-------------------------------------------------------------------------|
   // Variable Set Op                                                         |
   //

   //
   // ADD
   //

   DO_INIT(SETOP_ADD_AUTO32F)
   DO_INIT(SETOP_ADD_AUTO32I)
   DO_INIT(SETOP_ADD_AUTO32U)

   DO_INIT(SETOP_ADD_POINTER32F)
   DO_INIT(SETOP_ADD_POINTER32I)
   DO_INIT(SETOP_ADD_POINTER32U)

   DO_INIT(SETOP_ADD_REGISTER32F)
   DO_INIT(SETOP_ADD_REGISTER32I)
   DO_INIT(SETOP_ADD_REGISTER32U)

   DO_INIT(SETOP_ADD_STATIC32F)
   DO_INIT(SETOP_ADD_STATIC32I)
   DO_INIT(SETOP_ADD_STATIC32U)

   //
   // AND
   //

   DO_INIT(SETOP_AND_AUTO32)

   DO_INIT(SETOP_AND_POINTER32)

   DO_INIT(SETOP_AND_REGISTER32)

   DO_INIT(SETOP_AND_STATIC32)

   //
   // DEC
   //

   DO_INIT(SETOP_DEC_AUTO32F)
   DO_INIT(SETOP_DEC_AUTO32I)
   DO_INIT(SETOP_DEC_AUTO32U)

   DO_INIT(SETOP_DEC_POINTER32F)
   DO_INIT(SETOP_DEC_POINTER32I)
   DO_INIT(SETOP_DEC_POINTER32U)

   DO_INIT(SETOP_DEC_REGISTER32F)
   DO_INIT(SETOP_DEC_REGISTER32I)
   DO_INIT(SETOP_DEC_REGISTER32U)

   DO_INIT(SETOP_DEC_STATIC32F)
   DO_INIT(SETOP_DEC_STATIC32I)
   DO_INIT(SETOP_DEC_STATIC32U)

   //
   // DIV
   //

   DO_INIT(SETOP_DIV_AUTO32F)
   DO_INIT(SETOP_DIV_AUTO32I)
   DO_INIT(SETOP_DIV_AUTO32U)

   DO_INIT(SETOP_DIV_POINTER32F)
   DO_INIT(SETOP_DIV_POINTER32I)
   DO_INIT(SETOP_DIV_POINTER32U)

   DO_INIT(SETOP_DIV_REGISTER32F)
   DO_INIT(SETOP_DIV_REGISTER32I)
   DO_INIT(SETOP_DIV_REGISTER32U)

   DO_INIT(SETOP_DIV_STATIC32F)
   DO_INIT(SETOP_DIV_STATIC32I)
   DO_INIT(SETOP_DIV_STATIC32U)

   //
   // INC
   //

   DO_INIT(SETOP_INC_AUTO32F)
   DO_INIT(SETOP_INC_AUTO32I)
   DO_INIT(SETOP_INC_AUTO32U)

   DO_INIT(SETOP_INC_POINTER32F)
   DO_INIT(SETOP_INC_POINTER32I)
   DO_INIT(SETOP_INC_POINTER32U)

   DO_INIT(SETOP_INC_REGISTER32F)
   DO_INIT(SETOP_INC_REGISTER32I)
   DO_INIT(SETOP_INC_REGISTER32U)

   DO_INIT(SETOP_INC_STATIC32F)
   DO_INIT(SETOP_INC_STATIC32I)
   DO_INIT(SETOP_INC_STATIC32U)

   //
   // IOR
   //

   DO_INIT(SETOP_IOR_AUTO32)

   DO_INIT(SETOP_IOR_POINTER32)

   DO_INIT(SETOP_IOR_REGISTER32)

   DO_INIT(SETOP_IOR_STATIC32)

   //
   // LSH (Left Shift)
   //

   DO_INIT(SETOP_LSH_AUTO32)

   DO_INIT(SETOP_LSH_POINTER32)

   DO_INIT(SETOP_LSH_REGISTER32)

   DO_INIT(SETOP_LSH_STATIC32)

   //
   // MOD
   //

   DO_INIT(SETOP_MOD_AUTO32F)
   DO_INIT(SETOP_MOD_AUTO32I)
   DO_INIT(SETOP_MOD_AUTO32U)

   DO_INIT(SETOP_MOD_POINTER32F)
   DO_INIT(SETOP_MOD_POINTER32I)
   DO_INIT(SETOP_MOD_POINTER32U)

   DO_INIT(SETOP_MOD_REGISTER32F)
   DO_INIT(SETOP_MOD_REGISTER32I)
   DO_INIT(SETOP_MOD_REGISTER32U)

   DO_INIT(SETOP_MOD_STATIC32F)
   DO_INIT(SETOP_MOD_STATIC32I)
   DO_INIT(SETOP_MOD_STATIC32U)

   //
   // MUL
   //

   DO_INIT(SETOP_MUL_AUTO32F)
   DO_INIT(SETOP_MUL_AUTO32I)
   DO_INIT(SETOP_MUL_AUTO32U)

   DO_INIT(SETOP_MUL_POINTER32F)
   DO_INIT(SETOP_MUL_POINTER32I)
   DO_INIT(SETOP_MUL_POINTER32U)

   DO_INIT(SETOP_MUL_REGISTER32F)
   DO_INIT(SETOP_MUL_REGISTER32I)
   DO_INIT(SETOP_MUL_REGISTER32U)

   DO_INIT(SETOP_MUL_STATIC32F)
   DO_INIT(SETOP_MUL_STATIC32I)
   DO_INIT(SETOP_MUL_STATIC32U)

   //
   // RSH (Right Shift)
   //

   DO_INIT(SETOP_RSH_AUTO32)

   DO_INIT(SETOP_RSH_POINTER32)

   DO_INIT(SETOP_RSH_REGISTER32)

   DO_INIT(SETOP_RSH_STATIC32)

   //
   // SUB
   //

   DO_INIT(SETOP_SUB_AUTO32F)
   DO_INIT(SETOP_SUB_AUTO32I)
   DO_INIT(SETOP_SUB_AUTO32U)

   DO_INIT(SETOP_SUB_POINTER32F)
   DO_INIT(SETOP_SUB_POINTER32I)
   DO_INIT(SETOP_SUB_POINTER32U)

   DO_INIT(SETOP_SUB_REGISTER32F)
   DO_INIT(SETOP_SUB_REGISTER32I)
   DO_INIT(SETOP_SUB_REGISTER32U)

   DO_INIT(SETOP_SUB_STATIC32F)
   DO_INIT(SETOP_SUB_STATIC32I)
   DO_INIT(SETOP_SUB_STATIC32U)

   //
   // XOR
   //

   DO_INIT(SETOP_XOR_AUTO32)

   DO_INIT(SETOP_XOR_POINTER32)

   DO_INIT(SETOP_XOR_REGISTER32)

   DO_INIT(SETOP_XOR_STATIC32)


   //-------------------------------------------------------------------------|
   // Miscellaneous                                                           |
   //

   DO_INIT(MISC_NATIVE)

   DO_INIT(MISC_NEGATE32F)
   DO_INIT(MISC_NEGATE32I)


   //-------------------------------------------------------------------------|
   // ACS                                                                     |
   //

   DO_INIT(ACS_GAME_GET_PLAYERCOUNT)
   DO_INIT(ACS_GAME_GET_SKILL)
   DO_INIT(ACS_GAME_GET_THINGCOUNT_SID)
   DO_INIT(ACS_GAME_GET_THINGCOUNT_SID_IMM)
   DO_INIT(ACS_GAME_GET_TIME)
   DO_INIT(ACS_GAME_GET_TYPE)

   DO_INIT(ACS_GET_MAPREGISTER)
   DO_INIT(ACS_GET_WORLDREGISTER)

   //
   // Activator Line
   //
   DO_INIT(ACS_LINE_CLR_SPECIAL)
   DO_INIT(ACS_LINE_GET_SIDE)

   //
   // Line Tag
   //
   DO_INIT(ACS_LTAG_SET_BLOCK)
   DO_INIT(ACS_LTAG_SET_SPECIAL)
   DO_INIT(ACS_LTAG_SET_TEXTURE)

   DO_INIT(ACS_MISC_RANDOM)
   DO_INIT(ACS_MISC_RANDOM_IMM)

   DO_INIT(ACS_SCRIPT_RESTART)
   DO_INIT(ACS_SCRIPT_SUSPEND)
   DO_INIT(ACS_SCRIPT_TERMINATE)

   DO_INIT(ACS_SET_MAPREGISTER)
   DO_INIT(ACS_SET_WORLDREGISTER)

   DO_INIT(ACS_SETOP_ADD_MAPREGISTER)
   DO_INIT(ACS_SETOP_ADD_WORLDREGISTER)

   DO_INIT(ACS_SETOP_AND_MAPREGISTER)
   DO_INIT(ACS_SETOP_AND_WORLDREGISTER)

   DO_INIT(ACS_SETOP_DEC_MAPREGISTER)
   DO_INIT(ACS_SETOP_DEC_WORLDREGISTER)

   DO_INIT(ACS_SETOP_DIV_MAPREGISTER)
   DO_INIT(ACS_SETOP_DIV_WORLDREGISTER)

   DO_INIT(ACS_SETOP_INC_MAPREGISTER)
   DO_INIT(ACS_SETOP_INC_WORLDREGISTER)

   DO_INIT(ACS_SETOP_IOR_MAPREGISTER)
   DO_INIT(ACS_SETOP_IOR_WORLDREGISTER)

   DO_INIT(ACS_SETOP_MOD_MAPREGISTER)
   DO_INIT(ACS_SETOP_MOD_WORLDREGISTER)

   DO_INIT(ACS_SETOP_MUL_MAPREGISTER)
   DO_INIT(ACS_SETOP_MUL_WORLDREGISTER)

   DO_INIT(ACS_SETOP_SUB_MAPREGISTER)
   DO_INIT(ACS_SETOP_SUB_WORLDREGISTER)

   DO_INIT(ACS_SETOP_XOR_MAPREGISTER)
   DO_INIT(ACS_SETOP_XOR_WORLDREGISTER)

   DO_INIT(ACS_SOUND_AMBIENT)
   DO_INIT(ACS_SOUND_MTAG)
   DO_INIT(ACS_SOUND_SECTOR)
   DO_INIT(ACS_SOUND_SEQUENCE)

   DO_INIT(ACS_SPECIAL_EXEC1)
   DO_INIT(ACS_SPECIAL_EXEC1_IMM)
   DO_INIT(ACS_SPECIAL_EXEC2)
   DO_INIT(ACS_SPECIAL_EXEC2_IMM)
   DO_INIT(ACS_SPECIAL_EXEC3)
   DO_INIT(ACS_SPECIAL_EXEC3_IMM)
   DO_INIT(ACS_SPECIAL_EXEC4)
   DO_INIT(ACS_SPECIAL_EXEC4_IMM)
   DO_INIT(ACS_SPECIAL_EXEC5)
   DO_INIT(ACS_SPECIAL_EXEC5_IMM)

   //
   // Sector Tag
   //
   DO_INIT(ACS_STAG_SET_TEXTURE_CEILING)
   DO_INIT(ACS_STAG_SET_TEXTURE_CEILING_IMM)
   DO_INIT(ACS_STAG_SET_TEXTURE_FLOOR)
   DO_INIT(ACS_STAG_SET_TEXTURE_FLOOR_IMM)

   DO_INIT(ACS_WAIT_POLYOBJECT)
   DO_INIT(ACS_WAIT_POLYOBJECT_IMM)
   DO_INIT(ACS_WAIT_SCRIPT)
   DO_INIT(ACS_WAIT_SCRIPT_IMM)
   DO_INIT(ACS_WAIT_SECTOR)
   DO_INIT(ACS_WAIT_SECTOR_IMM)
   DO_INIT(ACS_WAIT_TICS)
   DO_INIT(ACS_WAIT_TICS_IMM)


   //-------------------------------------------------------------------------|
   // ACS Common Extensions                                                   |
   //


   //-------------------------------------------------------------------------|
   // ACS Extensions                                                          |
   //

   DO_INIT(ACSE_FUNC_CALL_IMM)
   DO_INIT(ACSE_FUNC_CALLVOID_IMM)
   DO_INIT(ACSE_FUNC_RETN)
   DO_INIT(ACSE_FUNC_RETNVOID)

   DO_INIT(ACSE_GAME_EXEC)
   DO_INIT(ACSE_GAME_EXEC_IMM)
   DO_INIT(ACSE_GAME_GET_CVAR)
   DO_INIT(ACSE_GAME_GET_INVASIONSTATE)
   DO_INIT(ACSE_GAME_GET_INVASIONWAVE)
   DO_INIT(ACSE_GAME_GET_LEVELINFO)
   DO_INIT(ACSE_GAME_GET_TEAMINFO_PLAYERCOUNT_BLUE)
   DO_INIT(ACSE_GAME_GET_TEAMINFO_PLAYERCOUNT_RED)
   DO_INIT(ACSE_GAME_GET_TEAMINFO_SCORE_BLUE)
   DO_INIT(ACSE_GAME_GET_TEAMINFO_SCORE_RED)
   DO_INIT(ACSE_GAME_GET_THINGCOUNT_STR)
   DO_INIT(ACSE_GAME_GET_TYPE_ONEFLAGCTF)
   DO_INIT(ACSE_GAME_GET_TYPE_SINGLEPLAYER)
   DO_INIT(ACSE_GAME_REPLACETEXTURES)
   DO_INIT(ACSE_GAME_SET_AIRCONTROL)
   DO_INIT(ACSE_GAME_SET_AIRCONTROL_IMM)
   DO_INIT(ACSE_GAME_SET_GRAVITY)
   DO_INIT(ACSE_GAME_SET_GRAVITY_IMM)
   DO_INIT(ACSE_GAME_SET_LEVEL)
   DO_INIT(ACSE_GAME_SET_MUSIC)
   DO_INIT(ACSE_GAME_SET_MUSIC_IMM)
   DO_INIT(ACSE_GAME_SET_MUSICLOCAL)
   DO_INIT(ACSE_GAME_SET_MUSICLOCAL_IMM)
   DO_INIT(ACSE_GAME_SET_MUSICST)
   DO_INIT(ACSE_GAME_SET_SKY)

   DO_INIT(ACSE_GET_GLOBALARRAY)
   DO_INIT(ACSE_GET_GLOBALREGISTER)
   DO_INIT(ACSE_GET_MAPARRAY)
   DO_INIT(ACSE_GET_WORLDARRAY)

   //
   // Activator Line
   //
   DO_INIT(ACSE_LINE_GET_OFFSETY)

   //
   // Line Tag
   //
   DO_INIT(ACSE_LTAG_SET_BLOCKMONSTER)

   //
   // Mobj ID
   //
   DO_INIT(ACSE_MID_GET)
   DO_INIT(ACSE_MID_SET)

   DO_INIT(ACSE_MISC_PLAYMOVIE)

   //
   // Mobj Tag
   //
   DO_INIT(ACSE_MTAG_ADD_INVENTORY)
   DO_INIT(ACSE_MTAG_CHK_TEXTURE_CEILING)
   DO_INIT(ACSE_MTAG_CHK_TEXTURE_FLOOR)
   DO_INIT(ACSE_MTAG_CLR_INVENTORY)
   DO_INIT(ACSE_MTAG_DAMAGE)
   DO_INIT(ACSE_MTAG_GET)
   DO_INIT(ACSE_MTAG_GET_ANGLE)
   DO_INIT(ACSE_MTAG_GET_CEILINGZ)
   DO_INIT(ACSE_MTAG_GET_CLASSIFICATION)
   DO_INIT(ACSE_MTAG_GET_FLOORZ)
   DO_INIT(ACSE_MTAG_GET_INVENTORY)
   DO_INIT(ACSE_MTAG_GET_LIGHTLEVEL)
   DO_INIT(ACSE_MTAG_GET_PITCH)
   DO_INIT(ACSE_MTAG_GET_X)
   DO_INIT(ACSE_MTAG_GET_Y)
   DO_INIT(ACSE_MTAG_GET_Z)
   DO_INIT(ACSE_MTAG_MORPH)
   DO_INIT(ACSE_MTAG_SET)
   DO_INIT(ACSE_MTAG_SET_ANGLE)
   DO_INIT(ACSE_MTAG_SET_CAMERATEXTURE)
   DO_INIT(ACSE_MTAG_SET_MARINESPRITE)
   DO_INIT(ACSE_MTAG_SET_MARINEWEAPON)
   DO_INIT(ACSE_MTAG_SET_PITCH)
   DO_INIT(ACSE_MTAG_SET_SPECIAL)
   DO_INIT(ACSE_MTAG_SET_STATE)
   DO_INIT(ACSE_MTAG_SET_XYZ)
   DO_INIT(ACSE_MTAG_SUB_INVENTORY)
   DO_INIT(ACSE_MTAG_UNMORPH)
   DO_INIT(ACSE_MTAG_USEINVENTORY)

   DO_INIT(ACSE_PLAYER_GET_CAMERA)
   DO_INIT(ACSE_PLAYER_GET_CLASS)
   DO_INIT(ACSE_PLAYER_GET_INFO)
   DO_INIT(ACSE_PLAYER_GET_INGAME)
   DO_INIT(ACSE_PLAYER_GET_INPUT)
   DO_INIT(ACSE_PLAYER_GET_ISBOT)

   DO_INIT(ACSE_SCREEN_FADE_STOP)
   DO_INIT(ACSE_SCREEN_FADE_RANGE)
   DO_INIT(ACSE_SCREEN_FADE_START)
   DO_INIT(ACSE_SCREEN_GET_HEIGHT)
   DO_INIT(ACSE_SCREEN_GET_WIDTH)
   DO_INIT(ACSE_SCREEN_SET_HUDSIZE)

   DO_INIT(ACSE_SCRIPT_RETURN)
   DO_INIT(ACSE_SCRIPT_SETRETURN)

   DO_INIT(ACSE_SET_GLOBALARRAY)
   DO_INIT(ACSE_SET_GLOBALREGISTER)
   DO_INIT(ACSE_SET_MAPARRAY)
   DO_INIT(ACSE_SET_WORLDARRAY)

   DO_INIT(ACSE_SETOP_ADD_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_ADD_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_ADD_MAPARRAY)
   DO_INIT(ACSE_SETOP_ADD_WORLDARRAY)

   DO_INIT(ACSE_SETOP_AND_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_AND_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_AND_MAPARRAY)
   DO_INIT(ACSE_SETOP_AND_MAPREGISTER)
   DO_INIT(ACSE_SETOP_AND_WORLDARRAY)
   DO_INIT(ACSE_SETOP_AND_WORLDREGISTER)

   DO_INIT(ACSE_SETOP_DEC_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_DEC_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_DEC_MAPARRAY)
   DO_INIT(ACSE_SETOP_DEC_WORLDARRAY)

   DO_INIT(ACSE_SETOP_DIV_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_DIV_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_DIV_MAPARRAY)
   DO_INIT(ACSE_SETOP_DIV_WORLDARRAY)

   DO_INIT(ACSE_SETOP_INC_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_INC_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_INC_MAPARRAY)
   DO_INIT(ACSE_SETOP_INC_WORLDARRAY)

   DO_INIT(ACSE_SETOP_IOR_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_IOR_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_IOR_MAPARRAY)
   DO_INIT(ACSE_SETOP_IOR_MAPREGISTER)
   DO_INIT(ACSE_SETOP_IOR_WORLDARRAY)
   DO_INIT(ACSE_SETOP_IOR_WORLDREGISTER)

   DO_INIT(ACSE_SETOP_LSH_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_LSH_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_LSH_MAPARRAY)
   DO_INIT(ACSE_SETOP_LSH_MAPREGISTER)
   DO_INIT(ACSE_SETOP_LSH_WORLDARRAY)
   DO_INIT(ACSE_SETOP_LSH_WORLDREGISTER)

   DO_INIT(ACSE_SETOP_MOD_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_MOD_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_MOD_MAPARRAY)
   DO_INIT(ACSE_SETOP_MOD_WORLDARRAY)

   DO_INIT(ACSE_SETOP_MUL_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_MUL_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_MUL_MAPARRAY)
   DO_INIT(ACSE_SETOP_MUL_WORLDARRAY)

   DO_INIT(ACSE_SETOP_RSH_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_RSH_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_RSH_MAPARRAY)
   DO_INIT(ACSE_SETOP_RSH_MAPREGISTER)
   DO_INIT(ACSE_SETOP_RSH_WORLDARRAY)
   DO_INIT(ACSE_SETOP_RSH_WORLDREGISTER)

   DO_INIT(ACSE_SETOP_SUB_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_SUB_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_SUB_MAPARRAY)
   DO_INIT(ACSE_SETOP_SUB_WORLDARRAY)

   DO_INIT(ACSE_SETOP_XOR_GLOBALARRAY)
   DO_INIT(ACSE_SETOP_XOR_GLOBALREGISTER)
   DO_INIT(ACSE_SETOP_XOR_MAPARRAY)
   DO_INIT(ACSE_SETOP_XOR_MAPREGISTER)
   DO_INIT(ACSE_SETOP_XOR_WORLDARRAY)
   DO_INIT(ACSE_SETOP_XOR_WORLDREGISTER)

   DO_INIT(ACSE_SOUND_THING)
   DO_INIT(ACSE_SOUND_AMBIENTLOCAL)

   DO_INIT(ACSE_SPAWN_POINT)
   DO_INIT(ACSE_SPAWN_POINT_IMM)
   DO_INIT(ACSE_SPAWN_PROJECTILE_SID)
   DO_INIT(ACSE_SPAWN_PROJECTILE_STR)
   DO_INIT(ACSE_SPAWN_SPOT)
   DO_INIT(ACSE_SPAWN_SPOT_ANGLE)
   DO_INIT(ACSE_SPAWN_SPOT_ANGLE_IMM)

   DO_INIT(ACSE_SPECIAL_EXEC5_RETN1)

   //
   // Sector Tag
   //
   DO_INIT(ACSE_STAG_DAMAGE)
   DO_INIT(ACSE_STAG_GET_LIGHTLEVEL)
   DO_INIT(ACSE_STAG_GET_THINGCOUNT_SID)
   DO_INIT(ACSE_STAG_GET_THINGCOUNT_STR)
   DO_INIT(ACSE_STAG_GET_Z_CEILING)
   DO_INIT(ACSE_STAG_GET_Z_FLOOR)
   DO_INIT(ACSE_STAG_SET_TRIGGER_CEILING)
   DO_INIT(ACSE_STAG_SET_TRIGGER_FLOOR)

   DO_INIT(ACSE_STRING_COPY_GLOBALRANGE)
   DO_INIT(ACSE_STRING_COPY_MAPRANGE)
   DO_INIT(ACSE_STRING_COPY_WORLDRANGE)
   DO_INIT(ACSE_STRING_GET_LENGTH)
   DO_INIT(ACSE_STRING_TAG)

   //
   // Activator Thing
   //
   DO_INIT(ACSE_THING_ADD_INVENTORY)
   DO_INIT(ACSE_THING_ADD_INVENTORY_IMM)
   DO_INIT(ACSE_THING_CHK_WEAPON)
   DO_INIT(ACSE_THING_CLR_INVENTORY)
   DO_INIT(ACSE_THING_GET_AMMOCAP)
   DO_INIT(ACSE_THING_GET_ARMOR)
   DO_INIT(ACSE_THING_GET_FRAGS)
   DO_INIT(ACSE_THING_GET_HEALTH)
   DO_INIT(ACSE_THING_GET_INVENTORY)
   DO_INIT(ACSE_THING_GET_INVENTORY_IMM)
   DO_INIT(ACSE_THING_GET_MID)
   DO_INIT(ACSE_THING_GET_MTAG)
   DO_INIT(ACSE_THING_GET_PLAYERNUMBER)
   DO_INIT(ACSE_THING_GET_SIGIL)
   DO_INIT(ACSE_THING_GET_TEAM)
   DO_INIT(ACSE_THING_SET_AMMOCAP)
   DO_INIT(ACSE_THING_SET_MID)
   DO_INIT(ACSE_THING_SET_MUGSHOT)
   DO_INIT(ACSE_THING_SET_WEAPON)
   DO_INIT(ACSE_THING_SUB_INVENTORY)
   DO_INIT(ACSE_THING_SUB_INVENTORY_IMM)
   DO_INIT(ACSE_THING_USEINVENTORY)

   DO_INIT(ACSE_TRANSLATION_END)
   DO_INIT(ACSE_TRANSLATION_PALETTE)
   DO_INIT(ACSE_TRANSLATION_RGB)
   DO_INIT(ACSE_TRANSLATION_START)

   DO_INIT(ACSE_TRIG_VECTORANGLE)


   //-------------------------------------------------------------------------|
   // ACS Printing                                                            |
   //

   DO_INIT(ACSP_CHARACTER)

   DO_INIT(ACSP_END)
   DO_INIT(ACSP_END_BOLD)
   DO_INIT(ACSP_END_ERROR)
   DO_INIT(ACSP_END_HUD)
   DO_INIT(ACSP_END_HUD_BOLD)
   DO_INIT(ACSP_END_LOG)
   DO_INIT(ACSP_END_OPT)
   DO_INIT(ACSP_END_STRING)

   DO_INIT(ACSP_KEYBIND)

   DO_INIT(ACSP_NUM_BIN32F)
   DO_INIT(ACSP_NUM_BIN32I)
   DO_INIT(ACSP_NUM_BIN32U)

   DO_INIT(ACSP_NUM_DEC32F)
   DO_INIT(ACSP_NUM_DEC32I)
   DO_INIT(ACSP_NUM_DEC32U)

   DO_INIT(ACSP_NUM_HEX32F)
   DO_INIT(ACSP_NUM_HEX32I)
   DO_INIT(ACSP_NUM_HEX32U)

   DO_INIT(ACSP_PLAYER_NAME)

   DO_INIT(ACSP_SET_FONT)
   DO_INIT(ACSP_SET_FONT_IMM)

   DO_INIT(ACSP_START)
   DO_INIT(ACSP_START_OPT)

   DO_INIT(ACSP_STRING)
   DO_INIT(ACSP_STRING_GLOBALARRAY)
   DO_INIT(ACSP_STRING_GLOBALRANGE)
   DO_INIT(ACSP_STRING_LOCALIZED)
   DO_INIT(ACSP_STRING_MAPARRAY)
   DO_INIT(ACSP_STRING_MAPRANGE)
   DO_INIT(ACSP_STRING_WORLDARRAY)
   DO_INIT(ACSP_STRING_WORLDRANGE)

// EOF

